In [1]:
from word2number import w2n

In [3]:
print (w2n.word_to_num("twenty four"))

24


In [4]:
import pandas as pd
import numpy as np
import sklearn.metrics as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [5]:
df=pd.read_csv('hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [7]:
df.experience=df.experience.fillna('Zero')

In [8]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [12]:
df.experience=df.experience.astype('str')

In [14]:
df.dtypes

experience                     object
test_score(out of 10)         float64
interview_score(out of 10)      int64
salary($)                       int64
dtype: object

In [22]:
 df.experience=df.experience.apply(w2n.word_to_num)
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [23]:
X=df.drop('salary($)', axis='columns')
y=df['salary($)']

In [24]:
X.head()

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6

In [25]:
y.head()

0    50000
1    45000
2    60000
3    65000
4    70000
Name: salary($), dtype: int64

In [29]:
X=X.fillna(method='ffill')

In [30]:
model=LinearRegression()
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
model.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [32]:
model.intercept_

14992.65144669314

In [33]:
model.predict([[2,9,6]])

array([53713.86677124])

In [34]:
model.predict([[12,10,10]])

array([93747.79628651])

In [36]:
import math
median_test_score=math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [37]:
X

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    7.0                           7
7          11                    7.0                           8

In [38]:
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000